  services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: go_app_container
      ports:
        - "8080:8080"
      env_file:
        - .env
      depends_on:
        - db
      networks:
        - my_network

    db:
      image: postgres:latest
      container_name: postgres_container
      ports:
        - "5432:5432"
      env_file:
        - .env
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - my_network

  volumes:
    postgres_data:

  networks:
    my_network:
      driver: bridge
